<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <link rel="icon" type="image/x-icon" href="/public/static/img/favicon.ico" />

    {% block styles %}
      <link rel="stylesheet" type="text/css" href="/public/static/webfonts/gill-sans.css">
    {% endblock styles %}

    {% block title %}{% endblock title %}

  </head>
  <body>
    {% block body %}{% endblock body %}
  </body>
</html>
