<html>
  <head>
    <meta charset="utf-8">

    <link rel="stylesheet" type="text/css" href="public/styles.css">
  </head>
  <body>
    <div class="container">
      <section class="header">
        <h1>Texas State Water Plan 2017</h1>
      </section>
      <section class="content">
        <div class="row">
          <div class="twelve columns">
            <div id="ReactApp"></div>
          </div>
        </div>
      </section>
    </div>
    
    <script type="text/javascript" src="public/bundle.js" charset="utf-8"></script>
  </body>
</html>
